// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jibe.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	jibe.proto

It has these top-level messages:
	IndexRequest
	IndexResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A queue entry is written by a trigger and read by a worker.
type IndexRequest struct {
	Id       string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Location string            `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	Values   map[string]string `protobuf:"bytes,3,rep,name=values" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *IndexRequest) Reset()                    { *m = IndexRequest{} }
func (m *IndexRequest) String() string            { return proto.CompactTextString(m) }
func (*IndexRequest) ProtoMessage()               {}
func (*IndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IndexRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IndexRequest) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *IndexRequest) GetValues() map[string]string {
	if m != nil {
		return m.Values
	}
	return nil
}

// Currently empty response. Might be extended in future.
type IndexResponse struct {
}

func (m *IndexResponse) Reset()                    { *m = IndexResponse{} }
func (m *IndexResponse) String() string            { return proto.CompactTextString(m) }
func (*IndexResponse) ProtoMessage()               {}
func (*IndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*IndexRequest)(nil), "protocol.IndexRequest")
	proto.RegisterType((*IndexResponse)(nil), "protocol.IndexResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Jibe service

type JibeClient interface {
	// Push an item to jibe for indexing.
	Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error)
}

type jibeClient struct {
	cc *grpc.ClientConn
}

func NewJibeClient(cc *grpc.ClientConn) JibeClient {
	return &jibeClient{cc}
}

func (c *jibeClient) Index(ctx context.Context, in *IndexRequest, opts ...grpc.CallOption) (*IndexResponse, error) {
	out := new(IndexResponse)
	err := grpc.Invoke(ctx, "/protocol.Jibe/Index", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Jibe service

type JibeServer interface {
	// Push an item to jibe for indexing.
	Index(context.Context, *IndexRequest) (*IndexResponse, error)
}

func RegisterJibeServer(s *grpc.Server, srv JibeServer) {
	s.RegisterService(&_Jibe_serviceDesc, srv)
}

func _Jibe_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JibeServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.Jibe/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JibeServer).Index(ctx, req.(*IndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Jibe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.Jibe",
	HandlerType: (*JibeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _Jibe_Index_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jibe.proto",
}

func init() { proto.RegisterFile("jibe.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0xca, 0x4c, 0x4a,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x1b, 0x19,
	0xb9, 0x78, 0x3c, 0xf3, 0x52, 0x52, 0x2b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8,
	0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53, 0x84, 0xa4,
	0xb8, 0x38, 0x72, 0xf2, 0x93, 0x13, 0x4b, 0x32, 0xf3, 0xf3, 0x24, 0x98, 0xc0, 0xa2, 0x70, 0xbe,
	0x90, 0x15, 0x17, 0x5b, 0x59, 0x62, 0x4e, 0x69, 0x6a, 0xb1, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0xb7,
	0x91, 0x92, 0x1e, 0xcc, 0x5c, 0x3d, 0x64, 0x33, 0xf5, 0xc2, 0xc0, 0x8a, 0x5c, 0xf3, 0x4a, 0x8a,
	0x2a, 0x83, 0xa0, 0x3a, 0xa4, 0x2c, 0xb9, 0xb8, 0x91, 0x84, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53,
	0x2b, 0xa1, 0xf6, 0x82, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x60, 0xa5, 0x50, 0x5b, 0x21, 0x1c, 0x2b,
	0x26, 0x0b, 0x46, 0x25, 0x7e, 0x2e, 0x5e, 0xa8, 0xf1, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x46,
	0x4e, 0x5c, 0x2c, 0x5e, 0x99, 0x49, 0xa9, 0x42, 0x56, 0x5c, 0xac, 0x60, 0x09, 0x21, 0x31, 0xec,
	0x0e, 0x91, 0x12, 0xc7, 0x10, 0x87, 0x98, 0xa0, 0xc4, 0x90, 0xc4, 0x06, 0x96, 0x31, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0x69, 0x2f, 0x6d, 0x27, 0x01, 0x00, 0x00,
}
